/**
 * Sample-Submissions für Pilot-Canvas-Demo
 * Simuliert zwei unabhängige Reviewer mit realistischen Abweichungen.
 *
 * Reviewer A: Leicht konservativer, neigt zu UNCERTAIN bei Grenzfällen
 * Reviewer B: Leicht aggressiver, tendiert zu konkreter Klasse auch bei dünner Evidenz
 */

import type { ReviewSubmission } from './review-types.js';

export const REVIEWER_A_SUBMISSIONS: ReviewSubmission[] = [
  {
    eventId: 'EVT-P01',
    reviewerId: 'RVW-A',
    reviewTimestamp: '2026-04-17T10:12:00Z',
    finalLabel: 'MASSIVE_DUMP',
    confidence: 0.95,
    alternativeLabel: null,
    secondaryReviewRequired: false,
    secondaryReviewReason: null,
    keyEvidence: ['Sell-Volume 91.8%', 'Preis -38.4% in 60 Min', '9/9 Metriken kritisch'],
    contradictingEvidence: [],
    detectionReasonSeen: false,
    reviewNote: 'Eindeutigster Fall im Set. Kein Zweifel.',
    dataQualityScore: 5,
  },
  {
    eventId: 'EVT-P02',
    reviewerId: 'RVW-A',
    reviewTimestamp: '2026-04-17T10:18:00Z',
    finalLabel: 'MASSIVE_DUMP',
    confidence: 0.91,
    alternativeLabel: null,
    secondaryReviewRequired: false,
    secondaryReviewReason: null,
    keyEvidence: ['Sell-Volume 85.7%', 'Preis -28.6%', '8/9 Metriken kritisch'],
    contradictingEvidence: ['Leicht höherer Buy-Anteil als P01'],
    detectionReasonSeen: false,
    reviewNote: 'Klar MASSIVE_DUMP. Etwas weniger extrem als P01.',
    dataQualityScore: 5,
  },
  {
    eventId: 'EVT-P03',
    reviewerId: 'RVW-A',
    reviewTimestamp: '2026-04-17T10:24:00Z',
    finalLabel: 'NORMAL_VOLATILITY',
    confidence: 0.93,
    alternativeLabel: null,
    secondaryReviewRequired: false,
    secondaryReviewReason: null,
    keyEvidence: ['Preis -4.2% in 60 Min', 'Buy/Sell-Ratio 48/52', 'Alle Metriken grün'],
    contradictingEvidence: [],
    detectionReasonSeen: false,
    reviewNote: 'Lehrbuchfall normale Volatilität.',
    dataQualityScore: 5,
  },
  {
    eventId: 'EVT-P04',
    reviewerId: 'RVW-A',
    reviewTimestamp: '2026-04-17T10:29:00Z',
    finalLabel: 'NORMAL_VOLATILITY',
    confidence: 0.87,
    alternativeLabel: 'BOT_ACTIVITY_NO_PRICE_IMPACT',
    secondaryReviewRequired: false,
    secondaryReviewReason: null,
    keyEvidence: ['+6.8% Preis, Volume-Ratio 1.8x Baseline', 'Keine kritischen Metriken', 'Stabile Liquidität'],
    contradictingEvidence: ['Volume-Ratio 1.8x leicht erhöht', 'Sniper-Count 2'],
    detectionReasonSeen: false,
    reviewNote: 'NORMAL_VOLATILITY mit leicht erhöhter Bot-Aktivität. Preiseffekt fehlt für BOT_ACTIVITY.',
    dataQualityScore: 5,
  },
  {
    eventId: 'EVT-P05',
    reviewerId: 'RVW-A',
    reviewTimestamp: '2026-04-17T10:38:00Z',
    finalLabel: 'ILLIQUID_RANDOM_MOVE',
    confidence: 0.78,
    alternativeLabel: 'DATA_INSUFFICIENT',
    secondaryReviewRequired: false,
    secondaryReviewReason: null,
    keyEvidence: ['Order-Book 2 Levels', 'Nur 28 Trades', 'Größte Order 41.3% des Vol'],
    contradictingEvidence: ['-22.8% könnte auch bei MASSIVE_DUMP auftreten'],
    detectionReasonSeen: false,
    reviewNote: 'Flash-Crash durch eine Riesenorder in illiquidem Markt. 71% Erholung bestätigt ILLIQUID. 7/9 Metriken verfügbar — knapp über DATA_INSUFFICIENT-Schwelle.',
    dataQualityScore: 2,
  },
  {
    eventId: 'EVT-P06',
    reviewerId: 'RVW-A',
    reviewTimestamp: '2026-04-17T10:47:00Z',
    finalLabel: 'UNCERTAIN',
    confidence: 0.62,
    alternativeLabel: 'ILLIQUID_RANDOM_MOVE',
    secondaryReviewRequired: true,
    secondaryReviewReason: 'ALT_LABEL_LOW_CONF',
    keyEvidence: ['Order-Book 3 Levels', 'Sell-Volume 77.9%', '-31.7% in 60 Min'],
    contradictingEvidence: ['4/9 Metriken kritisch spricht für MASSIVE_DUMP', 'Erholung nur 48% (nicht 50%-Whale-Schwelle)'],
    detectionReasonSeen: false,
    reviewNote: 'Grenzfall: Order-Book dünn (ILLIQUID) aber Sell-Druck hoch (MASSIVE_DUMP-Tendenz). Erholung 48% unter WHALE-Schwelle. Entscheide mich für UNCERTAIN mit ILLIQUID als wahrscheinlichste Klasse.',
    dataQualityScore: 3,
  },
  {
    eventId: 'EVT-P07',
    reviewerId: 'RVW-A',
    reviewTimestamp: '2026-04-17T10:54:00Z',
    finalLabel: 'WHALE_SELL_NO_CASCADE',
    confidence: 0.83,
    alternativeLabel: null,
    secondaryReviewRequired: false,
    secondaryReviewReason: null,
    keyEvidence: ['Whale 2.3% Supply identifiziert', 'Erholung 67% in 30 Min', 'Nur 1 Follow-Sell'],
    contradictingEvidence: ['Sell-Volume 68.8% etwas hoch'],
    detectionReasonSeen: false,
    reviewNote: 'Whale klar identifiziert, kaum Cascade, gute Erholung.',
    dataQualityScore: 5,
  },
  {
    eventId: 'EVT-P08',
    reviewerId: 'RVW-A',
    reviewTimestamp: '2026-04-17T11:02:00Z',
    finalLabel: 'BOT_ACTIVITY_NO_PRICE_IMPACT',
    confidence: 0.91,
    alternativeLabel: null,
    secondaryReviewRequired: false,
    secondaryReviewReason: null,
    keyEvidence: ['Bot-Prob 84%', '18 Jito-Bundles + 12 Sandwiches', 'Preis -1.8% bei 7.4x Volume-Spike'],
    contradictingEvidence: [],
    detectionReasonSeen: false,
    reviewNote: 'Klassisches Bot-Pattern. Kein Preiseffekt trotz extremem Volumen.',
    dataQualityScore: 5,
  },
  {
    eventId: 'EVT-P09',
    reviewerId: 'RVW-A',
    reviewTimestamp: '2026-04-17T11:14:00Z',
    finalLabel: 'UNCERTAIN',
    confidence: 0.64,
    alternativeLabel: 'ILLIQUID_RANDOM_MOVE',
    secondaryReviewRequired: true,
    secondaryReviewReason: 'CLASS_CONFLICT_MD_IL',
    keyEvidence: ['Order-Book 3 Levels + 84 Trades', 'Sell-Volume 81.6%', '-24.3% in 60 Min'],
    contradictingEvidence: ['6/9 Metriken kritisch — eher MASSIVE_DUMP-Profil', 'Schwache Erholung 31%'],
    detectionReasonSeen: false,
    reviewNote: 'Sehr schwierig. ILLIQUID-Signale (Order-Book, 84 Trades) vs. MASSIVE_DUMP-Signale (Metriken, Sell-Dominanz). Tendiere zu UNCERTAIN mit ILLIQUID als alternativeLabel nach S4-Baum-Logik.',
    dataQualityScore: 4,
  },
  {
    eventId: 'EVT-P10',
    reviewerId: 'RVW-A',
    reviewTimestamp: '2026-04-17T11:24:00Z',
    finalLabel: 'UNCERTAIN',
    confidence: 0.71,
    alternativeLabel: 'WHALE_SELL_NO_CASCADE',
    secondaryReviewRequired: true,
    secondaryReviewReason: 'ALT_LABEL_LOW_CONF',
    keyEvidence: ['Whale identifiziert 1.4% Supply', '4 Follow-Sells (Grenzbereich)', 'Erholung 42% < 50%-Schwelle'],
    contradictingEvidence: ['Cascade-Zahl 4 liegt im 3–5-Grenzbereich', '5/9 Metriken kritisch'],
    detectionReasonSeen: false,
    reviewNote: 'Klarer Grenzfall. Whale vorhanden, aber Cascade und Erholung erfüllen Whale-Kriterien nicht eindeutig. UNCERTAIN korrekt.',
    dataQualityScore: 5,
  },
];

export const REVIEWER_B_SUBMISSIONS: ReviewSubmission[] = [
  {
    eventId: 'EVT-P01',
    reviewerId: 'RVW-B',
    reviewTimestamp: '2026-04-17T10:15:00Z',
    finalLabel: 'MASSIVE_DUMP',
    confidence: 0.97,
    alternativeLabel: null,
    secondaryReviewRequired: false,
    secondaryReviewReason: null,
    keyEvidence: ['9/9 Metriken kritisch', 'Sell 91.8%', '-38.4%'],
    contradictingEvidence: [],
    detectionReasonSeen: false,
    reviewNote: 'Eindeutig.',
    dataQualityScore: 5,
  },
  {
    eventId: 'EVT-P02',
    reviewerId: 'RVW-B',
    reviewTimestamp: '2026-04-17T10:21:00Z',
    finalLabel: 'MASSIVE_DUMP',
    confidence: 0.89,
    alternativeLabel: null,
    secondaryReviewRequired: false,
    secondaryReviewReason: null,
    keyEvidence: ['Sell-Vol 85.7%', '-28.6%', '8/9 Metriken kritisch'],
    contradictingEvidence: [],
    detectionReasonSeen: false,
    reviewNote: 'Klar MASSIVE_DUMP.',
    dataQualityScore: 5,
  },
  {
    eventId: 'EVT-P03',
    reviewerId: 'RVW-B',
    reviewTimestamp: '2026-04-17T10:26:00Z',
    finalLabel: 'NORMAL_VOLATILITY',
    confidence: 0.94,
    alternativeLabel: null,
    secondaryReviewRequired: false,
    secondaryReviewReason: null,
    keyEvidence: ['Alle Metriken grün', 'Buy/Sell ausgeglichen', '-4.2%'],
    contradictingEvidence: [],
    detectionReasonSeen: false,
    reviewNote: 'Normaler Markt.',
    dataQualityScore: 5,
  },
  {
    eventId: 'EVT-P04',
    reviewerId: 'RVW-B',
    reviewTimestamp: '2026-04-17T10:31:00Z',
    finalLabel: 'NORMAL_VOLATILITY',
    confidence: 0.82,
    alternativeLabel: null,
    secondaryReviewRequired: false,
    secondaryReviewReason: null,
    keyEvidence: ['+6.8%', 'Keine kritischen Metriken', 'Spread stabil'],
    contradictingEvidence: ['Volume 1.8x erhöht', '2 Sniper-Txs'],
    detectionReasonSeen: false,
    reviewNote: 'Normal. Bot-Aktivität zu gering für BOT_ACTIVITY-Klasse.',
    dataQualityScore: 5,
  },
  {
    eventId: 'EVT-P05',
    reviewerId: 'RVW-B',
    reviewTimestamp: '2026-04-17T10:41:00Z',
    finalLabel: 'ILLIQUID_RANDOM_MOVE',
    confidence: 0.81,
    alternativeLabel: null,
    secondaryReviewRequired: false,
    secondaryReviewReason: null,
    keyEvidence: ['2 Order-Book-Levels', '28 Trades', 'Flash-Crash + 71% Erholung'],
    contradictingEvidence: ['2 Metriken fehlen'],
    detectionReasonSeen: false,
    reviewNote: 'Klares ILLIQUID: eine Order bewegt den Preis massiv, Markt erholt sich sofort.',
    dataQualityScore: 2,
  },
  {
    eventId: 'EVT-P06',
    reviewerId: 'RVW-B',
    reviewTimestamp: '2026-04-17T10:51:00Z',
    // B wählt hier MASSIVE_DUMP — Abweichung zu A (UNCERTAIN)
    finalLabel: 'MASSIVE_DUMP',
    confidence: 0.69,
    alternativeLabel: 'ILLIQUID_RANDOM_MOVE',
    secondaryReviewRequired: true,
    secondaryReviewReason: 'CLASS_CONFLICT_MD_IL',
    keyEvidence: ['Sell-Volume 77.9%', '-31.7%', '4/9 Metriken kritisch'],
    contradictingEvidence: ['Order-Book nur 3 Levels — Liquidität dünn', 'Erholung 48%'],
    detectionReasonSeen: false,
    reviewNote: 'Knapper Fall. Sell-Dominanz und Magnitude sprechen für MASSIVE_DUMP. Order-Book dünn, aber immer noch 3 Levels. Confidence 0.69 — grenzwertig. Secondary Review gesetzt.',
    dataQualityScore: 3,
  },
  {
    eventId: 'EVT-P07',
    reviewerId: 'RVW-B',
    reviewTimestamp: '2026-04-17T10:58:00Z',
    finalLabel: 'WHALE_SELL_NO_CASCADE',
    confidence: 0.80,
    alternativeLabel: null,
    secondaryReviewRequired: false,
    secondaryReviewReason: null,
    keyEvidence: ['Whale 2.3% Supply', 'Einzelorder 38.7% Vol', 'Erholung 67%'],
    contradictingEvidence: ['1 Follow-Sell vorhanden'],
    detectionReasonSeen: false,
    reviewNote: 'Whale klar, Erholung ausreichend, Cascade minimal.',
    dataQualityScore: 5,
  },
  {
    eventId: 'EVT-P08',
    reviewerId: 'RVW-B',
    reviewTimestamp: '2026-04-17T11:04:00Z',
    finalLabel: 'BOT_ACTIVITY_NO_PRICE_IMPACT',
    confidence: 0.93,
    alternativeLabel: null,
    secondaryReviewRequired: false,
    secondaryReviewReason: null,
    keyEvidence: ['84% Bot-Prob', 'Volume 7.4x Baseline', 'Preis -1.8% (minimal)'],
    contradictingEvidence: [],
    detectionReasonSeen: false,
    reviewNote: 'Eindeutig BOT.',
    dataQualityScore: 5,
  },
  {
    eventId: 'EVT-P09',
    reviewerId: 'RVW-B',
    reviewTimestamp: '2026-04-17T11:19:00Z',
    // B wählt MASSIVE_DUMP — Abweichung zu A (UNCERTAIN)
    finalLabel: 'MASSIVE_DUMP',
    confidence: 0.67,
    alternativeLabel: 'ILLIQUID_RANDOM_MOVE',
    secondaryReviewRequired: true,
    secondaryReviewReason: 'CLASS_CONFLICT_MD_IL',
    keyEvidence: ['6/9 Metriken kritisch', 'Sell-Vol 81.6%', '-24.3%'],
    contradictingEvidence: ['Order-Book 3 Levels — dünn', 'Nur 84 Trades'],
    detectionReasonSeen: false,
    reviewNote: 'Tendiere zu MASSIVE_DUMP wegen Metrik-Profil und hohem Sell-Druck. Order-Book dünn aber nicht leer. Confidence nur 0.67 — Secondary Review gesetzt.',
    dataQualityScore: 4,
  },
  {
    eventId: 'EVT-P10',
    reviewerId: 'RVW-B',
    reviewTimestamp: '2026-04-17T11:28:00Z',
    finalLabel: 'UNCERTAIN',
    confidence: 0.68,
    alternativeLabel: 'WHALE_SELL_NO_CASCADE',
    secondaryReviewRequired: true,
    secondaryReviewReason: 'ALT_LABEL_LOW_CONF',
    keyEvidence: ['Whale identifiziert', '4 Follow-Sells (Grenzbereich 3–5)', 'Erholung nur 42%'],
    contradictingEvidence: ['Cascade-Zahl 4 = knapp zu viel', 'Erholung unter 50%'],
    detectionReasonSeen: false,
    reviewNote: 'Gleiche Meinung wie ich vermutlich von Reviewer A: UNCERTAIN ist korrekt. Whale-Kriterien nicht vollständig erfüllt.',
    dataQualityScore: 5,
  },
];
